# -*- coding: utf-8 -*-
"""Reproduction package — the single path entry point.

`code/README.md` rule 3: *"No absolute paths, no personal directories. All paths
resolve from a single `paths_config.py` (or equivalent) at the repository root."*
Every script in this directory reads its input paths from here.

The contract mirrors `code/figures/paths_config.py`, so a reader who has already
configured one package has configured both:

| environment variable | meaning | default |
|---|---|---|
| `TWAS_REPO` | repository root (the directory holding `.zenodo.json`) | first ancestor with `.zenodo.json` |
| `TWAS_DATA_Z` | authoritative Z data layer | `<TWAS_REPO>/data/derived` |
| `REPRO_MS_DOCX` | the submitted manuscript `.docx` | `<TWAS_REPO>/manuscript/Manuscript.docx` |
| `REPRO_SI_DOCX` | the submitted Supporting Information `.docx` | `<TWAS_REPO>/manuscript/Supporting_Information.docx` |
| `REPRO_AF1_DOCX` | "Additional file 1", the review-revision SI that `m15_pc.py` patches | `<TWAS_REPO>/manuscript/Additional_file_1.docx` |
| `REPRO_MASHR_DB_DIR` | mashr eQTL model databases (third-party; not redistributed) | unset |
| `REPRO_GTEX_OFFICIAL_DIR` | the six official MetaXcan GTEx x FinnGen tables (not redistributed) | unset — the shipped wide table is used instead |

Three document classes are deliberately **not** tracked in this repository:
the submitted manuscripts, and the mashr model databases. Their paths therefore
have no working default; `need()` says exactly what to download and where to
point the variable.

Every shipped input is listed in `INPUTS.md` with its MD5 and byte count, and
the same hashes are asserted here. A run either matches them or says so.
"""
import csv
import gzip
import hashlib
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
_SENTINEL = '.zenodo.json'
_ENV_REPO = 'TWAS_REPO'


def _find_repo(start):
    """Walk up from `start` looking for the repository sentinel."""
    d = start
    for _ in range(8):
        if os.path.exists(os.path.join(d, _SENTINEL)):
            return d
        parent = os.path.dirname(d)
        if parent == d:
            break
        d = parent
    # Historical layout fallback: <repo>/code/analyses/reproduction_20261002/
    return os.path.dirname(os.path.dirname(os.path.dirname(start)))


REPO = os.environ.get(_ENV_REPO) or _find_repo(HERE)
DERIVED = os.environ.get('TWAS_DATA_Z') or os.path.join(REPO, 'data', 'derived')
GENOMEWIDE = os.path.join(DERIVED, 'genomewide')
SUPERSEDED = os.path.join(REPO, 'data', 'superseded')
RESULTS = os.path.join(HERE, 'results')
LOGS = os.path.join(HERE, 'logs')

#: The pre-correction layer. Named here only so scripts can assert they are NOT
#: reading it — it is never an input path.
FORBIDDEN = SUPERSEDED

# ---------------------------------------------------------------------------
# Shipped inputs. `md5` is asserted by `check_shipped()`; None means the file is
# recorded in INPUTS.md but regenerated by a caller-side step.
# ---------------------------------------------------------------------------
# NOTE ON THE RECORDED HASHES. These are the hashes of the files **as a fresh clone
# checks them out**, i.e. LF. They are deliberately NOT the hashes of the author's
# original CRLF copies, which differ by exactly one byte per line — and which the
# first version of this table recorded. The consequence was that `check_shipped()`
# passed on the machine that built the package and failed for every reader who cloned
# it. `.gitattributes` declares `eol=lf` for `*.csv`, `*.tsv` and `*.txt` precisely so
# that the checked-out bytes are platform-independent; re-record these only from a
# fresh clone.
_SH = 'ld'   # under <DERIVED>/
_GW = 'gw'   # under <DERIVED>/genomewide/

SHIPPED_SPEC = {
    'scz_z_4arm':         (_SH, 'scz_z_4arm.csv', 'b444a5d3652ff39d6a5723e96e2dce38', 662091),
    'gtex_Z':             (_SH, 'gtex_Z.csv', 'ac3e910b8e4da941f1bb71c5d2ccd018', 12990),
    'eqtlgen_Z':          (_SH, 'eqtlgen_Z.csv', 'a63773d394308cfbdbf9c8c4ed8e9385', 15653),
    'gene_groups':        (_SH, 'gene_groups.csv', 'f3f5ceda42cacadc5f78cec0f0899d12', 5610),
    'primary_arm':        (_SH, 'primary_arm_96pairs.csv', '95ad96362314861ce110610a66ffac39', 2842),
    'crosscohort':        (_SH, 'crosscohort.csv', '48c6012874f83fdc959432603fbc457f', 831),
    'hk_genes':           (_SH, 'hk_genes.txt', 'eb7c1a1156029e4118cb003f3be41178', 1468),
    'mashr_nsnps':        (_SH, 'mashr_nsnps.csv.gz', 'e3b549b55a509ed211e28245f316044d', 62725),
    'ukb_dr_dir':         (_SH, 'ukb_dr', None, None),
    # --- added 2026-10-02 (see 00_build_added_derived.py) ---
    'groups_json':        (_SH, 'groups.json', '5e4be2aa31fa0a87e5e4d0f0b81e26c4', 3753),
    'covariate_matrix':   (_SH, 'covariate_matrix.csv', '5efef7f83d3b8808eb0a0e7492bc0e0e', 6523),
    'hrt_source':         (_SH, 'hrt/Human_Mouse_Common.csv', '8403fef37ede36089b4a32b7ef95bae9', 15355),
    'rand_dr':            (_SH, 'hrt_random_control/official_rand_DR.csv', '5898558144bad62f8866f456666a35b0', 8050),
    'rand_dn':            (_SH, 'hrt_random_control/official_rand_DN.csv', '951d7a62d650ce02d78d91517bfc8c2c', 8045),
    'rand_dpn':           (_SH, 'hrt_random_control/official_rand_DPN.csv', '77885fdce68cc20ffe88f33611cb0c34', 8057),
    'pool_a':             (_SH, 's9_pools/POOL_A.txt', '83f9895b96780cd5a967e3475c8537a4', 80739),
    'both_a':             (_SH, 's9_pools/both_A.txt', '906bbc673d8c2cb1b3e356cb002a2497', 70865),
    'pool_818':           (_SH, 's9_pools/POOL_818.txt', 'b080de509b738e1ca4063502b2a5369e', 5078),
    'both_818':           (_SH, 's9_pools/both_818.txt', 'd61bf5c21ea6799199f3f9c988fa7578', 4758),
    'disease_blacklist':  (_SH, 's9_pools/disease_blacklist.txt', '1a150a298639bc9122fafbea9df68fc5', 844),
    'gtex_official_wide': (_SH, 'gtex_official_finngen/gtex_official_zscores_wide.csv.gz', '5c19740b0445e70d13936e939d5af558', 735045),
    # --- genome-wide weight-source layers ---
    'gw_eqz':             (_GW, 'eqz_full.csv.gz', '5c69596eb9e508123fb6cdd7948eda00', 136150),
    'gw_gtex_wb':         (_GW, 'gtex_official_Whole_Blood.csv.gz', '7775c350817879cdf55feddd9c59c5b0', 691052),
    'gw_gtex_nt':         (_GW, 'gtex_official_Nerve_Tibial.csv.gz', 'd16dac23cd360274c557c0b1dcfd6d4c', 857050),
    'gw_en_wb':           (_GW, 'en_official_en_Whole_Blood.csv.gz', 'a076675dea8c74347179c83e6d31cbb4', 490098),
    'gw_en_nt':           (_GW, 'en_official_en_Nerve_Tibial.csv.gz', 'd320ccb64ddb7a8dd243a78751527937', 672935),
}


def _build_shipped():
    out = {}
    for name, (kind, rel, h, sz) in SHIPPED_SPEC.items():
        base = GENOMEWIDE if kind == _GW else DERIVED
        out[name] = (os.path.join(base, *rel.split('/')), h, sz)
    return out


SHIPPED = _build_shipped()

#: Documents that accompany the submission and are not redistributed here.
DOCS = {
    'manuscript': dict(env='REPRO_MS_DOCX',
                       default=os.path.join(REPO, 'manuscript', 'Manuscript.docx'),
                       expect='Manuscript_GenetEpidemiol_20260930.docx',
                       md5='dbbe4f81a6fe9433b6a28019c6538eab', bytes=30524,
                       what='the submitted manuscript'),
    'si': dict(env='REPRO_SI_DOCX',
               default=os.path.join(REPO, 'manuscript', 'Supporting_Information.docx'),
               expect='Supporting_Information_GenetEpidemiol_20260930.docx',
               md5='bd50b7f819db7851c50ddfa76ae336eb', bytes=1462835,
               what='the submitted Supporting Information'),
    'af1': dict(env='REPRO_AF1_DOCX',
                default=os.path.join(REPO, 'manuscript', 'Additional_file_1.docx'),
                expect='Additional file 1_审稿意见修订_20260917.docx',
                md5=None, bytes=None,
                what='the Additional-file-1 SI revision that m15_pc.py reads'),
    'pred_manuscript': dict(env='REPRO_PRED_MS_DOCX',
                            default=os.path.join(REPO, 'manuscript', 'PredecessorManuscript.docx'),
                            expect='Manuscript.docx (the 2026-09-28 BMC final manuscript)',
                            md5=None, bytes=None,
                            what='the predecessor BMC submission manuscript, used by the '
                                 'bmc_ref/ cross-check only'),
    'pred_af1': dict(env='REPRO_PRED_AF1_DOCX',
                     default=os.path.join(REPO, 'manuscript', 'PredecessorAdditionalFile1.docx'),
                     expect='Additional_file_1.docx (the 2026-09-28 BMC Additional file 1)',
                     md5=None, bytes=None,
                     what='the predecessor BMC Additional file 1, used by the bmc_ref/ '
                          'cross-check only'),
}

#: Third-party / bulk layers that are not redistributed (see INPUTS.md).
EXTERNAL_DIRS = {
    'mashr_db_dir': dict(env='REPRO_MASHR_DB_DIR',
                         default=None,
                         files={'mashr_Whole_Blood.db': ('1613d73c3fcc53a27dc1422118680b97', 4612096),
                                'mashr_Nerve_Tibial.db': ('9983e7b1557230162331839acf5ed228', 5910528)},
                         what='mashr eQTL model databases (two SQLite files)'),
    'gtex_official_dir': dict(env='REPRO_GTEX_OFFICIAL_DIR',
                              default=None,
                              files={'official_Nerve_Tibial_DN.csv': ('1dc9106b31369aa5115322bd03fd0b7a', 2256166),
                                     'official_Nerve_Tibial_DPN.csv': ('92b942f7437b65bb0dc2658e1eb6bccb', 2254949),
                                     'official_Nerve_Tibial_DR.csv': ('966e43e6dec03669fdd13ef44b6866d9', 2259160),
                                     'official_Whole_Blood_DN.csv': ('cce57111298a024b5e9ed5101c048f74', 1835601),
                                     'official_Whole_Blood_DPN.csv': ('c4bceab533b56ce928cf4c69e87462d8', 1834688),
                                     'official_Whole_Blood_DR.csv': ('57738c427b957c25a6f455f5ff22c4a0', 1837692)},
                              what='the six official MetaXcan GTEx x FinnGen tables '
                                   '(SPrediXcan on FinnGen R13 DR/DN/DPN x GTEx v8 MASHR '
                                   'Nerve_Tibial + Whole_Blood), 12.3 MB total'),
}


class MissingInput(SystemExit):
    """Raised with an actionable message rather than a traceback."""

    def __init__(self, what, path, how):
        super().__init__(
            '\n[missing input] %s\n'
            '  looked for : %s\n'
            '  expected   : %s\n'
            '  how to get : %s\n'
            '  override   : set the environment variable named above, or pass the\n'
            '               corresponding command-line flag (see --help).\n' % (
                what, path, _EXPECT.get(what, 'see INPUTS.md'), how))


_EXPECT = {}


def need(logical_or_path, what=None, how=None):
    """Resolve and existence-check, printing an actionable message."""
    p = get(logical_or_path) if logical_or_path in SHIPPED or logical_or_path in DOCS else logical_or_path
    if not os.path.exists(p):
        raise MissingInput(what or logical_or_path, p, how or 'see INPUTS.md')
    return p


def get(logical):
    """Path for a shipped input or a submission document."""
    if logical in SHIPPED:
        return SHIPPED[logical][0]
    if logical in DOCS:
        d = DOCS[logical]
        p = os.environ.get(d['env']) or d['default']
        return p
    raise KeyError('unknown logical input: %r' % logical)


def doc(logical):
    """Resolve a submission document, with a message naming the file to supply."""
    d = DOCS[logical]
    p = os.environ.get(d['env']) or d['default']
    if not os.path.exists(p):
        exp = d['expect']
        hint = ('%s; the file distributed with the submission is named "%s"'
                % (d['what'], exp)) if exp else d['what']
        if d['md5']:
            hint += ' (md5 %s, %s bytes)' % (d['md5'], format(d['bytes'], ','))
        raise MissingInput(logical, p, hint + '. Set %s=/path/to/%s' % (d['env'], exp or 'file'))
    return p


def external_dir(logical):
    """Resolve a non-redistributed bulk directory (mashr models, raw MetaXcan runs)."""
    d = EXTERNAL_DIRS[logical]
    root = os.environ.get(d['env']) or d['default']
    if not root or not os.path.isdir(root):
        lines = ['  files needed:']
        for fn, (h, sz) in d['files'].items():
            lines.append('    %-38s md5=%s bytes=%s' % (fn, h, sz))
        raise MissingInput(logical, root or ('$%s (unset)' % d['env']),
                           '%s. Not redistributed — see INPUTS.md for the acquiry route.\n%s'
                           % (d['what'], '\n'.join(lines)))
    return root


# ---------------------------------------------------------------------------
# Reading helpers
# ---------------------------------------------------------------------------
def open_text(path, encoding='utf-8-sig'):
    """Open plain or gzip-compressed text transparently."""
    if str(path).endswith('.gz'):
        return io.TextIOWrapper(gzip.open(path, 'rb'), encoding=encoding, newline='')
    return open(path, encoding=encoding, newline='')


def rows(path):
    """list[list[str]] for a CSV/TSV, gzip-aware."""
    with open_text(path) as f:
        return list(csv.reader(f))


def dict_rows(path):
    with open_text(path) as f:
        return list(csv.DictReader(f))


def md5(path):
    h = hashlib.md5()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()


def content_md5(path):
    """MD5 of the *decompressed* bytes for a `.gz` file, of the raw bytes otherwise.

    Five inputs ship gzipped to keep the repository small. Hashing the compressed
    bytes would make an input's recorded hash depend on the compressor, so the
    scripts record this instead and the numbers stay comparable with the run that
    produced the published values.
    """
    if str(path).endswith('.gz'):
        h = hashlib.md5()
        with gzip.open(path, 'rb') as f:
            for chunk in iter(lambda: f.read(1 << 20), b''):
                h.update(chunk)
        return h.hexdigest()
    return md5(path)


def describe_inputs(paths):
    """`{name: {'md5', 'bytes', 'content_md5'}}` for a mapping of name -> path."""
    out = {}
    for name, p in paths.items():
        rec = {'md5': md5(p), 'bytes': os.path.getsize(p)}
        if str(p).endswith('.gz'):
            rec['content_md5'] = content_md5(p)
        out[name] = rec
    return out


def check_shipped():
    """Assert every shipped input is present and, where recorded, byte-exact."""
    bad = []
    for name, (p, h, sz) in SHIPPED.items():
        if not os.path.exists(p):
            bad.append((name, 'MISSING', p))
            continue
        if os.path.isdir(p):
            continue
        if h and md5(p) != h:
            bad.append((name, 'MD5 MISMATCH', p))
        elif sz and os.path.getsize(p) != sz:
            bad.append((name, 'SIZE MISMATCH', p))
    return bad


#: The official MetaXcan layer used to live at `data/processed_officialZ/`.
#: It was renamed to `data/derived/` in the 2026-10-02 reorganisation and five of
#: its files were renamed with it. Scripts that quote an old name resolve here.
OFFICIAL_Z_RENAME = {
    'scz_z_4arm_official.csv': 'scz_z_4arm.csv',
    'gtex_official_Z.csv': 'gtex_Z.csv',
    'eqtlgen_official_Z.csv': 'eqtlgen_Z.csv',
    'gene_groups_TableS1_official.csv': 'gene_groups.csv',
    'primary_arm_96pairs_official.csv': 'primary_arm_96pairs.csv',
    'crosscohort_TableS4_official.csv': 'crosscohort.csv',
}


def officialZ(name):
    """Resolve a legacy `processed_officialZ` filename to its `data/derived/` path."""
    return os.path.join(DERIVED, OFFICIAL_Z_RENAME.get(name, name))


# ---------------------------------------------------------------------------
# Supporting-Information table extraction (replaces pre-extracted .tsv files)
# ---------------------------------------------------------------------------
_W = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'


def _para_text(p):
    out = []
    for n in p.iter():
        if n.tag == _W + 't':
            out.append(n.text or '')
        elif n.tag == _W + 'tab':
            out.append('\t')
        elif n.tag == _W + 'br':
            out.append('\n')
    return ''.join(out)


def si_tables(path=None):
    """Extract every table from the Supporting Information `.docx`.

    Returns a list of dicts: `{'title', 'rows', 'note', 'index'}` where `rows` is a
    rectangular `list[list[str]]` with gridSpan/vMerge expanded so columns align.
    Extracting from the `.docx` directly means the package does not need the
    pre-extracted TSVs that the diagnostic scripts originally read.
    """
    import zipfile
    from xml.etree import ElementTree as ET

    path = path or doc('si')
    z = zipfile.ZipFile(path)
    body = ET.fromstring(z.read('word/document.xml')).find(_W + 'body')
    children = list(body)
    out = []
    for k, c in enumerate(children):
        if c.tag != _W + 'tbl':
            continue
        title = ''
        for j in range(k - 1, -1, -1):
            if children[j].tag == _W + 'p' and _para_text(children[j]).strip():
                title = _para_text(children[j]).strip()
                break
        note = ''
        for j in range(k + 1, len(children)):
            if children[j].tag == _W + 'p' and _para_text(children[j]).strip():
                note = _para_text(children[j]).strip()
                break
        rows = []
        for tr in c.findall(_W + 'tr'):
            row = []
            for tc in tr.findall(_W + 'tc'):
                txt = '\n'.join(_para_text(p) for p in tc.findall(_W + 'p')).strip()
                span = 1
                pr = tc.find(_W + 'tcPr')
                if pr is not None:
                    gs = pr.find(_W + 'gridSpan')
                    if gs is not None:
                        span = int(gs.get(_W + 'val'))
                    vm = pr.find(_W + 'vMerge')
                    if vm is not None and (vm.get(_W + 'val') or 'continue') == 'continue':
                        txt = ''
                row.append(txt)
                row.extend(['<span>'] * (span - 1))
            rows.append(row)
        width = max((len(r) for r in rows), default=0)
        for r in rows:
            r.extend([''] * (width - len(r)))
        out.append({'index': len(out), 'title': title, 'note': note, 'rows': rows})
    return out


def si_table_by_address(address, path=None):
    """Fetch `Table S13` (or `S4a`) from the Supporting Information by its label."""
    m = re.match(r'\s*S?(\d+[a-z]?)\s*$', address.strip(), re.I)
    if not m:
        raise ValueError('not a table address: %r' % address)
    want = m.group(1).lower()
    for t in si_tables(path):
        lab = re.match(r'\s*Table\s*S?(\d+[a-z]?)', t['title'], re.I)
        if lab and lab.group(1).lower() == want:
            return t
    raise KeyError('Supporting Information has no table %s' % address)


def si_table_rows(address, path=None):
    """Rectangular rows (header at index 0) for `Table S13` and friends."""
    return si_table_by_address(address, path)['rows']


def si_rows_by_object(i, path=None):
    """Rows for table *object* `i`, i.e. the order the tables appear in the docx.

    The submitted Supporting Information places `Table S1` at object 0; because
    S5 is split into S5a and S5b the mapping `object i = Table S(i+1)` holds for
    the whole document (31 objects, S1-S30).
    """
    return si_tables(path)[i]['rows']


def report():
    print('  %-22s = %s' % ('REPO', REPO))
    for k in ('DERIVED', 'GENOMEWIDE', 'SUPERSEDED', 'RESULTS', 'LOGS', 'FORBIDDEN'):
        print('  %-22s = %s' % (k, globals()[k]))
    print()
    print('  shipped inputs:')
    for name, (p, h, sz) in SHIPPED.items():
        mark = 'ok ' if os.path.exists(p) else 'MISSING'
        print('    [%s] %-20s %s' % (mark, name, p))
    print()
    print('  submission documents (not redistributed):')
    for k, d in DOCS.items():
        p = os.environ.get(d['env']) or d['default']
        mark = 'ok ' if os.path.exists(p) else 'not supplied'
        print('    [%-12s] %-12s %s' % (mark, k, p))
    bad = check_shipped()
    print()
    print('  self-check: %s' % ('all shipped inputs present and byte-exact'
                                if not bad else '%d problem(s): %s' % (len(bad), bad)))
    return bad


def cli_path(name, default=None):
    """Read `--<name> PATH` from argv (also `--<name>=PATH`), falling back to a default."""
    flag = '--' + name.replace('_', '-')
    argv = sys.argv[1:]
    for i, a in enumerate(argv):
        if a == flag and i + 1 < len(argv):
            return argv[i + 1]
        if a.startswith(flag + '='):
            return a.split('=', 1)[1]
    return default


def apply_cli_overrides():
    """Map `--repo-root`, `--ms-docx`, `--si-docx`, `--af1-docx`, `--mashr-db-dir`
    and `--gtex-official-dir` onto the corresponding environment variables, then
    recompute the derived constants. Call once, first thing, from a script body."""
    pairs = [('repo_root', _ENV_REPO), ('ms_docx', DOCS['manuscript']['env']),
             ('si_docx', DOCS['si']['env']), ('af1_docx', DOCS['af1']['env']),
             ('mashr_db_dir', EXTERNAL_DIRS['mashr_db_dir']['env']),
             ('gtex_official_dir', EXTERNAL_DIRS['gtex_official_dir']['env'])]
    for flag, env in pairs:
        v = cli_path(flag)
        if v:
            os.environ[env] = v
    reload_paths()


def reload_paths():
    """Recompute every module-level path from the current environment."""
    global REPO, DERIVED, GENOMEWIDE, SUPERSEDED, SHIPPED, FORBIDDEN
    REPO = os.environ.get(_ENV_REPO) or _find_repo(HERE)
    DERIVED = os.environ.get('TWAS_DATA_Z') or os.path.join(REPO, 'data', 'derived')
    GENOMEWIDE = os.path.join(DERIVED, 'genomewide')
    SUPERSEDED = os.path.join(REPO, 'data', 'superseded')
    FORBIDDEN = SUPERSEDED
    SHIPPED = _build_shipped()
    for _k, _d in DOCS.items():
        _d['default'] = os.path.join(REPO, 'manuscript', os.path.basename(_d['default']))


for _k, _d in DOCS.items():
    _EXPECT[_k] = _d['what']

if __name__ == '__main__':
    apply_cli_overrides()
    # Non-zero exit on a mismatch. The first version only printed the verdict, so a
    # release gate could not distinguish "all shipped inputs byte-exact" from "11 of
    # them altered" without parsing English prose — and a check that cannot fail the
    # build is not a gate.
    sys.exit(1 if report() else 0)
