#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate metadata/provenance.json.

Hashes **every file tracked by git** and records the external-input manifest.
Run before each release; `scripts/cut_release.sh` fails the release if the
manifest does not cover the tree.

    python scripts/collect_provenance.py

WHY EVERY TRACKED FILE, NOT A HAND-PICKED LIST
----------------------------------------------
The first version hashed three directories (`data/derived`, `code/analyses/recovered`,
`code/figures`) and registered 36 files against a tree of 281. Nothing forced the two
numbers to agree, so the 59-file reproduction package added on 2026-10-02 was
registered **zero** times, and the top-level README's claim that *"every input file is
pinned by checksum in metadata/provenance.json"* was false for every one of its
eight external inputs. The coverage gate in `cut_release.sh` now makes that
impossible: manifest entries + declared exclusions must equal `git ls-files`.

The hashes are taken from the **index** — i.e. from the bytes a fresh clone receives —
not from the working tree. Hashing the working tree made the manifest verify on the
machine that produced it and fail anywhere the line endings differed; `index_blobs()`
records what a reader actually gets.

The only exclusion is the manifest itself, which cannot hash itself.

The external-input half is documentation, not discovery: those resources are still
not redistributed here, but their hashes are now **held** — 2026-10-03, the copies
that produced the reported numbers were hashed on disk and the upstream stage was
re-run against them (code/run_upstream.sh), so the `sha256` fields record a
verified identity rather than `not-held`. Identifiers, versions and the retrieval
date come from Supporting Information Note S4.
"""
import hashlib
import json
import os
import platform
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT = os.path.join(REPO, 'metadata', 'provenance.json')

# Tracked files that cannot carry a meaningful hash, with the reason. Everything
# else in `git ls-files` must appear in `files`, or cut_release.sh fails.
EXCLUDED = [
    ('metadata/provenance.json',
     'the manifest cannot hash itself; its own content is regenerated by this script'),
]

# ---------------------------------------------------------------------------
# Inputs of the reproduction package that are NOT redistributed here. Measured on
# the machine that produced `code/analyses/reproduction_20261002/results/`, so a
# reader can confirm they hold the same files. `md5` is what the package's scripts
# print; `sha256` is what this manifest records. Full acquiry routes:
# `code/analyses/reproduction_20261002/INPUTS.md`.
# ---------------------------------------------------------------------------
REPRO_INPUTS = [
    {"logical": "manuscript", "file": "Manuscript_GenetEpidemiol_20260930.docx",
     "env_var": "REPRO_MS_DOCX", "bytes": 30523,
     "md5": "a6f7521b98efa0e2ef247664e2f0db3a",
     "sha256": "ce48e337bb37a9724ec2039413d795da6ae3662c5fc4c85f52b168e83370f9a6",
     "route": "accompanies the submission; obtain from the journal",
     "produces_results": True,
     "later_revision": {"label": "2026-10-03", "file": "Manuscript_GenetEpidemiol_20260930_rev2.docx",
                        "bytes": 30524, "md5": "ee64dfde3903585c3dadfd8b3b257f50",
                        "sha256": "69045bb6bd600850a32cc0e674313cca9407e37f1d1dfed79b6ece118f71c76c",
                        "change": "Methods: Python 3.13.0 -> 3.13.12, to agree with env/environment.yml"}},
    {"logical": "si", "file": "Supporting_Information_GenetEpidemiol_20260930.docx",
     "env_var": "REPRO_SI_DOCX", "bytes": 1462835,
     "md5": "bd50b7f819db7851c50ddfa76ae336eb",
     "sha256": "132d5eb080f0021e6ee180c4b7736ada27e35a5d8e457d29815992945d17ac73",
     "route": "accompanies the submission; obtain from the journal",
     "produces_results": True,
     "later_revision": {"label": "2026-10-03", "file": "Supporting_Information_GenetEpidemiol_20260930_rev2.docx",
                        "bytes": 1463194, "md5": "72f955c9294d5228c57288ba93617f1e",
                        "sha256": "81692586c4164286096f6c48fd289fa7ec32d6be9c2d7fbb4d32c09c02484dd8",
                        "change": "Note S4: per-resource retrieval dates; Note S4 Python 3.13.0 -> 3.13.12; Table S5a note: row-3 Q convention stated, full-precision value 76.27 given"}},
    {"logical": "af1", "file": "Additional file 1_审稿意见修订_20260917.docx",
     "env_var": "REPRO_AF1_DOCX", "bytes": None, "md5": None,
     "sha256": "c76f3f55b173f16b0bbedf36b9ab6d4ba382e2e54b54497a75dfb77048620c47",
     "route": "the Additional-file-1 revision that the S20 generator patches; held by the authors"},
    {"logical": "mashr_Whole_Blood.db", "file": "mashr_Whole_Blood.db",
     "env_var": "REPRO_MASHR_DB_DIR", "bytes": 4612096,
     "md5": "1613d73c3fcc53a27dc1422118680b97",
     "sha256": "1f4abfeea5f0ed122e812112821cd3626f3cbde72044e5a283830e8c8e13ba0f",
     "route": "third-party mashr eQTL models; not redistributed (data/README.md). Only needed to re-derive the Table S9 pools"},
    {"logical": "mashr_Nerve_Tibial.db", "file": "mashr_Nerve_Tibial.db",
     "env_var": "REPRO_MASHR_DB_DIR", "bytes": 5910528,
     "md5": "9983e7b1557230162331839acf5ed228",
     "sha256": "48dda44649b12a046023301cdc537189a5395f266f1fb8adb3833602791a380c",
     "route": "as above"},
    {"logical": "gtex_official_dir/*.csv", "file": "official_{Nerve_Tibial,Whole_Blood}_{DR,DN,DPN}.csv",
     "env_var": "REPRO_GTEX_OFFICIAL_DIR", "bytes": 12328056, "md5": None, "sha256": None,
     "route": "official MetaXcan v0.8.1 output; regenerate with code/run_spredixcan.sh. A flattened, precision-preserving equivalent ships as data/derived/gtex_official_finngen/"},
]

# Supporting Information Note S4 — identifiers, versions, retrieval date.
#
# `sha256` / `md5` / `bytes` are those of the copy that produced the reported
# numbers, recorded 2026-10-03 and re-verified by re-running the upstream stage
# against them (see code/run_upstream.sh and data/external/README.md). The files
# are still NOT redistributed — the hashes are what a reader checks a download
# against, with scripts/verify_external_inputs.py.
#
# `files` is a list because several inputs are one resource in more than one file,
# and because two are distributed under a filename that differs from the canonical
# one used here (recorded per entry as `download_name`).
EXTERNAL = [
    {"id": "FinnGen", "role": "primary GWAS input: DR / DN / DPN",
     "version": "Data Freeze 13 (R13)",
     "source_url": "https://www.finngen.fi/en/access_results",
     "files": [
         {"name": "finngen_R13_DM_RETINOPATHY_EXMORE.gz", "bytes": 799133923,
          "sha256": "92652925b89943fd216510d82622baec424b7713076734728cb46443ccb4d79a",
          "md5": "7cee13550d6075cad5941484013ab3f8"},
         {"name": "finngen_R13_DM_NEPHROPATHY.gz", "bytes": 801346330,
          "sha256": "9b17cbc3fb233df8113740a571f53e8efbfb0ee5f26ad23bd2640ffab35be69f",
          "md5": "f6a494a2b6e24bbedc68470d91843437"},
         {"name": "finngen_R13_DM_NEUROPATHY.gz", "bytes": 800964581,
          "sha256": "5a7d603866e887b3d10dbd7b49d2f54aea79b535342e7bbc7c6058bb980f0c53",
          "md5": "a40fd725f4bba44396b805d75f67b0bb"},
         {"name": "finngen_R13_manifest.tsv", "bytes": 820805,
          "sha256": "c9caafa9b98ee5ef050a705766bd1c451fc2154fb8e81b069022012a2f75ae20",
          "md5": "a70f4ecb57acf7c23e8f5d71be11d936"},
     ]},
    {"id": "GCST90043640", "role": "UK Biobank diabetic retinopathy GWAS (PheCode 250.7); cross-cohort arm",
     "version": "as distributed by GWAS Catalog",
     "source_url": "https://www.ebi.ac.uk/gwas/studies/GCST90043640",
     "citation": "Publication recorded by GWAS Catalog: Jiang L, Zheng Z, Fang H, Yang J. Nat Genet 2021;53:1616-1621. doi:10.1038/s41588-021-00954-4",
     "files": [
         {"name": "GCST90043640.h.tsv.gz", "bytes": 528201989,
          "sha256": "3776c85ada92559b4c6a66e27cbb0e40fa45963ce7c9f1131cd8df5e60878557",
          "md5": "a802753ce87d30de09e3bc2df15c9b8c",
          "download_name": "34737426-GCST90043640-EFO_0003770.h (1).tsv.gz"},
         {"name": "GCST90043640_buildGRCh37.tsv.gz", "bytes": 445327939,
          "sha256": "f84387729df2d608fa77907184f54dc32265a2c5b448a7ba81c8bc4a0c9518a3",
          "md5": "9ac919a05dbd8f3e2c405520b6aa870e"},
     ]},
    {"id": "GCST90018832", "role": "cross-population diabetic nephropathy meta-analysis (DN check)",
     "version": "as distributed by GWAS Catalog",
     "source_url": "https://www.ebi.ac.uk/gwas/studies/GCST90018832",
     "files": [
         {"name": "meta_egfr_dmstrat_stage1plus2.txt.gz", "bytes": 178400853,
          "sha256": "141114f3ae9add8a5b568b24b87bf833de4dff25fb94d66519c36f7fe8e3413f",
          "md5": "ffe5a12a04492085043741ea2f0bad96"},
     ]},
    {"id": "PGC3_SCZ_wave3", "role": "independent-trait genome-wide benchmark", "version": "schizophrenia wave 3 (scz2022)",
     "source_url": "https://pgc.unc.edu/for-researchers/download-results/",
     "files": [
         {"name": "PGC3_SCZ_wave3.european.autosome.public.v3.vcf.tsv.gz", "bytes": 239710564,
          "sha256": "dbba3a85575c99fd1c2e3497d0c7a44539ccfdbf2e69742f8bdbda879230bcd7",
          "md5": "6ebe2376f5cda972d37efa0f214c4df0"},
     ]},
    {"id": "GTEx_v8_MASHR", "role": "eQTL weight source A: Nerve_Tibial and Whole_Blood",
     "version": "GTEx v8 MASHR models", "source_url": "https://predictdb.org/post/2021/07/21/gtex-v8-models-on-eqtl-and-sqtl",
     "files": [
         {"name": "mashr_Whole_Blood.db", "bytes": 4612096,
          "sha256": "1f4abfeea5f0ed122e812112821cd3626f3cbde72044e5a283830e8c8e13ba0f",
          "md5": "1613d73c3fcc53a27dc1422118680b97"},
         {"name": "mashr_Nerve_Tibial.db", "bytes": 5910528,
          "sha256": "48dda44649b12a046023301cdc537189a5395f266f1fb8adb3833602791a380c",
          "md5": "9983e7b1557230162331839acf5ed228"},
         {"name": "gtex_v8_mashr_snp_covariance.txt.gz", "bytes": 2362720,
          "sha256": "5c90428be350797bcd8f855d54bddece888a63a9ea864e35fe39f6ea44b5a9c2",
          "md5": "cc2a4c861095ea359da15cc31733702f"},
     ]},
    {"id": "eQTLGen_phaseI", "role": "eQTL weight source B", "version": "phase I cis-eQTL, N = 31,684",
     "source_url": "https://www.eqtlgen.org/",
     "files": [
         {"name": "2019-12-11-cis-eQTLsFDR0.05-ProbeLevel-CohortInfoRemoved-BonferroniAdded.txt.gz", "bytes": 322775879,
          "sha256": "8d963046d7b74cf3533c3510614cdc724e7ad0e325a3d2f7cca63ad13661b4c4",
          "md5": "3073e2f39d0847692c053949e85723d9"},
         {"name": "eQTLGen_Whole_Blood.db", "bytes": 4866048, "derived": True,
          "sha256": "413c4fff25c1820fd92f11f4370e25f3b82ea2ecd5a84ff0643d5f750312fa3c",
          "md5": "aefbe7d485181145bd1e3ceffea2cfd6"},
     ]},
    {"id": "1000G_phase3_EUR", "role": "linkage-disequilibrium reference panel", "version": "Phase 3 European panel",
     "source_url": "https://www.internationalgenome.org/",
     "files": [
         {"name": "g1000_eur.zip", "bytes": 511626945,
          "sha256": "83a48fd9dcaa0b9a874b18c63143a4ede93f05505b215b0bd8790130a0d7a954",
          "md5": "1919cb5c79bbe7871aed71ae4abe6217"},
     ]},
    {"id": "ProteomeXchange_iProX", "role": "RNA pull-down LC-MS/MS",
     "version": "PXD083775 (iProX IPX0019439000, subproject IPX0019439001)",
     "source_url": "https://proteomecentral.proteomexchange.org/",
     "files": [
         {"name": "RNApull_down_MS_results.zip", "bytes": 21500065,
          "sha256": "c50e44b1c9ab2dcca46576ec0859ae2b12baa91360f9e97a232a72d39c810a4c",
          "md5": "cba90b3492f608a6005bbfb4c2f71783",
          "download_name": "RNApull down MS实验结果.zip"},
     ]},
]

# ---------------------------------------------------------------------------
# Retrieval dates, per resource — NOT one date for all eight.
#
# Supporting Information Note S4 states a single sentence: "every resource was
# retrieved on 8 September 2026". That is not what the filesystem shows. The copies
# that produced the reported numbers (identified by the SHA-256 in EXTERNAL above)
# carry dates from 2026-06-22 to 2026-07-17, and the GTEx model databases carry the
# PredictDB build date 2019-10-03 because they arrive inside a tarball that preserves
# it. Four of the eight therefore disagree with the blanket statement.
#
# So the manifest records what is *verifiable*: the date of the hashed copy as it
# sits on disk, plus what that date is a date *of* — because for an archived payload
# the meaningful date is the extraction, not the file's internal timestamp.
#
# When the submitted Supporting Information is next revised, Note S4 should carry
# these per-resource dates instead of the blanket sentence. Until then, the
# discrepancy is recorded here rather than smoothed over.
# ---------------------------------------------------------------------------
EXTERNAL_RETRIEVAL = {
    "FinnGen": ("2026-06-24",
                "download date of the three .gz endpoint files (and of the manifest, extracted 2026-06-25)"),
    "GCST90043640": ("2026-06-23",
                     "download date of the GRCh37 build; the harmonised .h.tsv.gz is dated 2026-06-24"),
    "GCST90018832": ("2026-06-25", "download date of the DN meta-analysis deposit"),
    "PGC3_SCZ_wave3": ("2026-07-17", "download date of the European-subset VCF"),
    "GTEx_v8_MASHR": ("2026-06-26",
                      "extraction date of the PredictDB bundle; the .db payloads keep their "
                      "2019-10-03 build timestamp inside the tarball"),
    "eQTLGen_phaseI": ("2026-06-24", "download date of the cis-eQTL summary statistics"),
    "1000G_phase3_EUR": ("2026-06-24", "download date of the g1000_eur bundle"),
    "ProteomeXchange_iProX": ("2026-06-22", "date of the RNA pull-down LC-MS/MS result archive"),
}

RETRIEVAL_CAVEAT = (
    "These dates are those of the hashed copy on the filesystem — the evidence available — "
    "not a restatement of Supporting Information Note S4, which gives one date "
    "(8 September 2026) for all eight resources. The two disagree for four of them; the "
    "discrepancy is recorded in data/external/README.md, 'Retrieve date', and Note S4 should "
    "carry these per-resource dates when the Supporting Information is next revised."
)

ANCESTRY_NOTE = (
    "For every GWAS resource, record the COMPLETE population composition of the source and "
    "state separately which subset was used. GCST90018832, for example, is a cross-population "
    "diabetic-nephropathy resource that includes East Asian participants alongside European "
    "participants; a table note listing only the European component is incomplete, and a "
    "Limitations statement that says 'all GWAS analyzed here comprise participants of European "
    "ancestry' contradicts the Methods. Both defects existed in an earlier revision."
)


def sha256(path, chunk=1 << 20):
    h = hashlib.sha256()
    with open(path, 'rb') as fh:
        for block in iter(lambda: fh.read(chunk), b''):
            h.update(block)
    return h.hexdigest()


def tracked_files():
    """`git ls-files`, as repository-relative POSIX paths, sorted."""
    out = subprocess.run(['git', 'ls-files', '-z'], cwd=REPO,
                         stdout=subprocess.PIPE, check=True).stdout
    return sorted(p.decode('utf-8') for p in out.split(b'\0') if p)


def index_blobs():
    """`path -> content bytes`, taken from the INDEX, not the working tree.

    WHY THE INDEX. Hashing the working tree records bytes that depend on the
    platform: a Windows checkout of a `eol=lf` file can differ from a Linux one,
    and any script that writes a log or a CSV with Python's default text mode puts
    CRLF back. Both make the manifest verify on the machine that produced it and
    fail for a reader who cloned — which is the opposite of the point. The index
    content IS what a fresh clone receives, so that is what gets hashed.

    Returns (blobs, missing) where `blobs` maps path -> bytes and `missing` lists
    paths whose object is not in the store.
    """
    raw = subprocess.run(['git', 'ls-files', '-s', '-z'], cwd=REPO,
                         stdout=subprocess.PIPE, check=True).stdout
    sha_by_path = {}
    for rec in raw.split(b'\0'):
        if not rec:
            continue
        meta, _, path = rec.partition(b'\t')
        parts = meta.split()
        if len(parts) >= 2:
            sha_by_path[path.decode('utf-8')] = parts[1].decode('ascii')

    sha_list = sorted(set(sha_by_path.values()))
    feed = b''.join(s.encode('ascii') + b'\n' for s in sha_list)
    out = subprocess.run(['git', 'cat-file', '--batch'], cwd=REPO, input=feed,
                         stdout=subprocess.PIPE, check=True).stdout

    blobs, pos, missing = {}, 0, []
    for sha in sha_list:
        nl = out.find(b'\n', pos)
        header = out[pos:nl].split()
        if len(header) < 3 or header[1] != b'blob':
            missing.append(sha)
            pos = nl + 1
            continue
        size = int(header[2])
        blobs[sha] = out[nl + 1: nl + 1 + size]
        pos = nl + 1 + size + 1                    # skip the trailing newline
    by_path = {p: blobs.get(s) for p, s in sha_by_path.items()}
    return by_path, set(missing)


def _env_versions():
    """Version string for `generated_by.analysis_env`, read from the shipped pins.

    These used to be a free-text literal that said "Python 3.13.0" while
    `env/environment.yml` pinned 3.13.12 — the manifest disagreed with the
    environment it claimed to describe, and nothing caught it because no gate
    reads that field. Deriving the string from the pin files makes the two
    impossible to disagree. Falls back to the literal only if a pin cannot be
    parsed, and says so rather than guessing.
    """
    py = r = None
    try:
        with open(os.path.join(REPO, 'env', 'environment.yml'), encoding='utf-8') as f:
            m = re.search(r'^\s*-\s*python\s*=\s*([0-9][0-9.]*)', f.read(), re.M)
            if m:
                py = m.group(1)
    except OSError:
        pass
    try:
        with open(os.path.join(REPO, 'env', 'renv.lock'), encoding='utf-8') as f:
            m = re.search(r'"R"\s*:\s*\{\s*"Version"\s*:\s*"([0-9][0-9.]*)"', f.read())
            if m:
                r = m.group(1)
    except OSError:
        pass
    if not (py and r):
        return ('Python 3.13.12 / R 4.5.2 with MatchIt, pinned as env/environment.yml and '
                'env/renv.lock (version strings could not be read from the pins)')
    return ('Python %s / R %s with MatchIt, pinned as env/environment.yml and env/renv.lock'
            % (py, r))


def main():
    excluded_paths = {p for p, _ in EXCLUDED}
    blobs, missing = index_blobs()
    files, skipped = [], []
    for rel in tracked_files():
        if rel in excluded_paths:
            continue
        content = blobs.get(rel)
        if content is None:
            skipped.append({'path': rel,
                            'reason': 'staged object not readable as a blob%s'
                                      % (' (object missing)' if missing else '')})
            continue
        files.append({'path': rel, 'bytes': len(content),
                      'sha256': hashlib.sha256(content).hexdigest()})
    files.sort(key=lambda x: x['path'])

    excluded = [{'path': p, 'reason': r} for p, r in EXCLUDED]
    excluded += skipped
    tracked_count = len(tracked_files())

    external = []
    for row in EXTERNAL:
        artefacts = row.get("files", [])
        held = [f for f in artefacts if f.get("sha256")]
        retrieved, basis = EXTERNAL_RETRIEVAL.get(row["id"], ("unknown", "not recorded"))
        entry = {
            "id": row["id"], "role": row["role"], "version": row["version"],
            "source_url": row["source_url"],
            "retrieved": retrieved,
            "retrieved_basis": basis,
            "retrieval_note": RETRIEVAL_CAVEAT,
            "sha256": (held[0]["sha256"] if len(held) == 1 else
                       ("held — %d artefacts, see 'files'" % len(held) if held else "not-held")),
            "sha256_note": ("Hash of the copy that produced the reported numbers. Recorded 2026-10-03, "
                            "and re-verified by re-running the upstream stage against it "
                            "(code/run_upstream.sh). Check a download with "
                            "scripts/verify_external_inputs.py."),
            "files": artefacts,
        }
        if row.get("citation"):
            entry["citation"] = row["citation"]
        external.append(entry)

    doc = {
        "_note": ("Provenance manifest. Regenerate with scripts/collect_provenance.py before each "
                  "release. 'external_inputs' is documentation; 'files' hashes every file tracked "
                  "by git, apart from the declared 'excluded' entries. "
                  "scripts/cut_release.sh asserts len(files) + len(excluded) == git ls-files."),
        "schema_version": "3.0",
        "generated_by": {
            "script": "scripts/collect_provenance.py",
            "python": sys.version.split()[0],
            "platform": platform.platform(),
            "metaxcan": "MetaXcan v0.8.1 (official binary)",
            "analysis_env": _env_versions(),
        },
        "external_inputs": external,
        "repro_inputs": REPRO_INPUTS,
        "repro_inputs_note": ("Inputs of code/analyses/reproduction_20261002/ that are NOT "
                              "redistributed with this archive. Hashes were measured on the machine "
                              "that produced that package's results/. Shipped inputs are covered by "
                              "'files' above; the full manifest is "
                              "code/analyses/reproduction_20261002/INPUTS.md."),
        "external_input_caveat": ANCESTRY_NOTE,
        "files": files,
        "file_count": len(files),
        "excluded": excluded,
        "tracked_file_count": tracked_count,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        json.dump(doc, fh, indent=1, ensure_ascii=False)
        fh.write('\n')
    print('wrote %s' % OUT)
    print('  tracked %d, hashed %d, excluded %d, external inputs %d, reproduction inputs %d'
          % (tracked_count, len(files), len(excluded), len(external), len(REPRO_INPUTS)))
    if len(files) + len(excluded) != tracked_count:
        print('  !! COVERAGE MISMATCH — cut_release.sh will refuse the release')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
