#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate metadata/provenance.json.

Hashes **every file tracked by git** and records the external-input manifest.
Run before each release; `scripts/cut_release.sh` fails the release if the
manifest does not cover the tree.

    python scripts/collect_provenance.py

WHY EVERY TRACKED FILE, NOT A HAND-PICKED LIST
----------------------------------------------
The first version hashed three directories (`data/derived`, `code/analyses/recovered`,
`code/figures`) and registered 36 files against a tree of 281. Nothing forced the two
numbers to agree, so the 59-file reproduction package added on 2026-10-02 was
registered **zero** times, and the top-level README's claim that *"every input file is
pinned by checksum in metadata/provenance.json"* was false for every one of its
eight external inputs. The coverage gate in `cut_release.sh` now makes that
impossible: manifest entries + declared exclusions must equal `git ls-files`.

The only exclusion is the manifest itself, which cannot hash itself.

The external-input half is documentation, not discovery: those resources are not
redistributed here, so their hashes are recorded as `not-held` until someone with
the file on disk records them. Identifiers, versions and the retrieval date come
from Supporting Information Note S4.
"""
import hashlib
import json
import os
import platform
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT = os.path.join(REPO, 'metadata', 'provenance.json')

# Tracked files that cannot carry a meaningful hash, with the reason. Everything
# else in `git ls-files` must appear in `files`, or cut_release.sh fails.
EXCLUDED = [
    ('metadata/provenance.json',
     'the manifest cannot hash itself; its own content is regenerated by this script'),
]

# ---------------------------------------------------------------------------
# Inputs of the reproduction package that are NOT redistributed here. Measured on
# the machine that produced `code/analyses/reproduction_20261002/results/`, so a
# reader can confirm they hold the same files. `md5` is what the package's scripts
# print; `sha256` is what this manifest records. Full acquiry routes:
# `code/analyses/reproduction_20261002/INPUTS.md`.
# ---------------------------------------------------------------------------
REPRO_INPUTS = [
    {"logical": "manuscript", "file": "Manuscript_GenetEpidemiol_20260930.docx",
     "env_var": "REPRO_MS_DOCX", "bytes": 30524,
     "md5": "dbbe4f81a6fe9433b6a28019c6538eab",
     "sha256": "a8c15af5e3dba4ebe3f286e435721f96e9cc192f2c1019cc35b63254352bfa1e",
     "route": "accompanies the submission; obtain from the journal"},
    {"logical": "si", "file": "Supporting_Information_GenetEpidemiol_20260930.docx",
     "env_var": "REPRO_SI_DOCX", "bytes": 1462835,
     "md5": "bd50b7f819db7851c50ddfa76ae336eb",
     "sha256": "132d5eb080f0021e6ee180c4b7736ada27e35a5d8e457d29815992945d17ac73",
     "route": "accompanies the submission; obtain from the journal"},
    {"logical": "af1", "file": "Additional file 1_审稿意见修订_20260917.docx",
     "env_var": "REPRO_AF1_DOCX", "bytes": None, "md5": None,
     "sha256": "c76f3f55b173f16b0bbedf36b9ab6d4ba382e2e54b54497a75dfb77048620c47",
     "route": "the Additional-file-1 revision that the S20 generator patches; held by the authors"},
    {"logical": "mashr_Whole_Blood.db", "file": "mashr_Whole_Blood.db",
     "env_var": "REPRO_MASHR_DB_DIR", "bytes": 4612096,
     "md5": "1613d73c3fcc53a27dc1422118680b97",
     "sha256": "1f4abfeea5f0ed122e812112821cd3626f3cbde72044e5a283830e8c8e13ba0f",
     "route": "third-party mashr eQTL models; not redistributed (data/README.md). Only needed to re-derive the Table S9 pools"},
    {"logical": "mashr_Nerve_Tibial.db", "file": "mashr_Nerve_Tibial.db",
     "env_var": "REPRO_MASHR_DB_DIR", "bytes": 5910528,
     "md5": "9983e7b1557230162331839acf5ed228",
     "sha256": "48dda44649b12a046023301cdc537189a5395f266f1fb8adb3833602791a380c",
     "route": "as above"},
    {"logical": "gtex_official_dir/*.csv", "file": "official_{Nerve_Tibial,Whole_Blood}_{DR,DN,DPN}.csv",
     "env_var": "REPRO_GTEX_OFFICIAL_DIR", "bytes": 12328056, "md5": None, "sha256": None,
     "route": "official MetaXcan v0.8.1 output; regenerate with code/run_spredixcan.sh. A flattened, precision-preserving equivalent ships as data/derived/gtex_official_finngen/"},
]

# Supporting Information Note S4 — identifiers, versions, retrieval date.
EXTERNAL = [
    ("FinnGen", "primary GWAS input: DR / DN / DPN", "Data Freeze 13 (R13)",
     "https://www.finngen.fi/en/access_results"),
    ("GCST90043640", "UK Biobank diabetic retinopathy GWAS (PheCode 250.7); cross-cohort arm",
     "as distributed by GWAS Catalog", "https://www.ebi.ac.uk/gwas/studies/GCST90043640",
     "Publication recorded by GWAS Catalog: Jiang L, Zheng Z, Fang H, Yang J. Nat Genet 2021;53:1616-1621. doi:10.1038/s41588-021-00954-4"),
    ("GCST90018832", "cross-population diabetic nephropathy meta-analysis (DN check)",
     "as distributed by GWAS Catalog", "https://www.ebi.ac.uk/gwas/studies/GCST90018832"),
    ("PGC3_SCZ_wave3", "independent-trait genome-wide benchmark", "schizophrenia wave 3 (scz2022)",
     "https://pgc.unc.edu/for-researchers/download-results/"),
    ("GTEx_v8_MASHR", "eQTL weight source A: Nerve_Tibial and Whole_Blood",
     "GTEx v8 MASHR models", "https://predictdb.org/post/2021/07/21/gtex-v8-models-on-eqtl-and-sqtl"),
    ("eQTLGen_phaseI", "eQTL weight source B", "phase I cis-eQTL, N = 31,684",
     "https://www.eqtlgen.org/"),
    ("1000G_phase3_EUR", "linkage-disequilibrium reference panel", "Phase 3 European panel",
     "https://www.internationalgenome.org/"),
    ("ProteomeXchange_iProX", "RNA pull-down LC-MS/MS",
     "PXD083775 (iProX IPX0019439000, subproject IPX0019439001)",
     "https://proteomecentral.proteomexchange.org/"),
]

ANCESTRY_NOTE = (
    "For every GWAS resource, record the COMPLETE population composition of the source and "
    "state separately which subset was used. GCST90018832, for example, is a cross-population "
    "diabetic-nephropathy resource that includes East Asian participants alongside European "
    "participants; a table note listing only the European component is incomplete, and a "
    "Limitations statement that says 'all GWAS analyzed here comprise participants of European "
    "ancestry' contradicts the Methods. Both defects existed in an earlier revision."
)


def sha256(path, chunk=1 << 20):
    h = hashlib.sha256()
    with open(path, 'rb') as fh:
        for block in iter(lambda: fh.read(chunk), b''):
            h.update(block)
    return h.hexdigest()


def tracked_files():
    """`git ls-files`, as repository-relative POSIX paths, sorted."""
    out = subprocess.run(['git', 'ls-files', '-z'], cwd=REPO,
                         stdout=subprocess.PIPE, check=True).stdout
    return sorted(p.decode('utf-8') for p in out.split(b'\0') if p)


def main():
    excluded_paths = {p for p, _ in EXCLUDED}
    files, skipped = [], []
    for rel in tracked_files():
        if rel in excluded_paths:
            continue
        p = os.path.join(REPO, *rel.split('/'))
        if not os.path.isfile(p):
            skipped.append({'path': rel, 'reason': 'tracked but absent from the working tree'})
            continue
        files.append({'path': rel, 'bytes': os.path.getsize(p), 'sha256': sha256(p)})
    files.sort(key=lambda x: x['path'])

    excluded = [{'path': p, 'reason': r} for p, r in EXCLUDED]
    excluded += skipped
    tracked_count = len(tracked_files())

    external = []
    for row in EXTERNAL:
        rid, role, version, url = row[0], row[1], row[2], row[3]
        entry = {
            "id": rid, "role": role, "version": version, "source_url": url,
            "retrieved": "2026-09-08",
            "retrieval_note": "Supporting Information Note S4 states: 'Every resource was retrieved on 8 September 2026.'",
            "sha256": "not-held",
            "sha256_note": "Not redistributed with this archive. Record the hash the first time someone runs this against the downloaded file.",
        }
        if len(row) > 4:
            entry["citation"] = row[4]
        external.append(entry)

    doc = {
        "_note": ("Provenance manifest. Regenerate with scripts/collect_provenance.py before each "
                  "release. 'external_inputs' is documentation; 'files' hashes every file tracked "
                  "by git, apart from the declared 'excluded' entries. "
                  "scripts/cut_release.sh asserts len(files) + len(excluded) == git ls-files."),
        "schema_version": "3.0",
        "generated_by": {
            "script": "scripts/collect_provenance.py",
            "python": sys.version.split()[0],
            "platform": platform.platform(),
            "metaxcan": "MetaXcan v0.8.1 (official binary)",
            "analysis_env": "Python 3.13.0 / R 4.5.2 with MatchIt, pinned as env/environment.yml and env/renv.lock",
        },
        "external_inputs": external,
        "repro_inputs": REPRO_INPUTS,
        "repro_inputs_note": ("Inputs of code/analyses/reproduction_20261002/ that are NOT "
                              "redistributed with this archive. Hashes were measured on the machine "
                              "that produced that package's results/. Shipped inputs are covered by "
                              "'files' above; the full manifest is "
                              "code/analyses/reproduction_20261002/INPUTS.md."),
        "external_input_caveat": ANCESTRY_NOTE,
        "files": files,
        "file_count": len(files),
        "excluded": excluded,
        "tracked_file_count": tracked_count,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        json.dump(doc, fh, indent=1, ensure_ascii=False)
        fh.write('\n')
    print('wrote %s' % OUT)
    print('  tracked %d, hashed %d, excluded %d, external inputs %d, reproduction inputs %d'
          % (tracked_count, len(files), len(excluded), len(external), len(REPRO_INPUTS)))
    if len(files) + len(excluded) != tracked_count:
        print('  !! COVERAGE MISMATCH — cut_release.sh will refuse the release')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
